name: Decrypt Confidential File and Load into Pandas

on:
  push:
    branches:
      - main

jobs:
  decrypt-and-process:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Decrypt confidential.json.gpg
      env:
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/decrypted_file.json confidential.json.gpg

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # You can specify another version if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Load decrypted file into Pandas and print
      run: |
        python -c "
        import pandas as pd

        # Load the decrypted file into a pandas dataframe
        df = pd.read_json('$HOME/decrypted_file.json')

        # Print the dataframe with nice formatting
        with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.width', 1000):
            print(df)
        "
