name: black-formatting-check
on:
- push
- pull_request
permissions:
  contents: write
jobs:
  linter_name:
    name: runner / black
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: datadog/action-py-black-formatter@v2.1
      id: action_black
    - uses: reviewdog/action-suggester@v1
      with:
        tool_name: blackfmt
    - name: Set up Git
      run: |
        git config --local user.email "git@impulsleistung.de"
        git config --local user.name "GitHub Action"
    - name: Commit and push if there are changes
      run: |
        git add -A
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Automated commit by GitHub Action"
          git push
        fi