name: Test GITHUB_TOKEN

on: [push]

jobs:
  test-token:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # This step will try to list the repositories for the authenticated user
    - name: Test GITHUB_TOKEN
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user/repos
